const { neon } = require('@neondatabase/serverless');
const sql = neon('postgresql://neondb_owner:npg_M5fiq0KWyCbD@ep-wandering-union-aomf3qsq.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=require');
const crypto = require('crypto');

async function main() {
  const idC6 = 'd3332fd2-82e1-475e-a018-25e8169d5035'; // Rút gọn biểu thức
  const idC7 = 'c70c9499-c84d-4d26-9315-4030d966e430'; // Hệ thức lượng
  const idC12 = '6a26c4af-052b-4c6f-b127-1ca2339ef7ee'; // Bất đẳng thức và cực trị

  const user_id = '8316c34e-765d-4b8c-9364-b683a17e33f8';
  let allQS = [];

  // Chuyên đề 6: Rút gọn biểu thức (Vận dụng cao)
  allQS.push(
    { grade: 9, cat: idC6, code: 'T9-RUT-06', content: 'Cho $P = \\left(\\dfrac{\\sqrt{x}}{\\sqrt{x}-1} - \\dfrac{1}{x-\\sqrt{x}}\\right) : \\left(\\dfrac{1}{\\sqrt{x}+1} + \\dfrac{2}{x-1}\\right)$. Rút gọn $P$ (với $x > 0, x \\neq 1$).', answer: '$P = \\dfrac{x-1}{\\sqrt{x}}$.', solution: 'Ngoặc 1: $\\dfrac{\\sqrt{x}}{\\sqrt{x}-1} - \\dfrac{1}{\\sqrt{x}(\\sqrt{x}-1)} = \\dfrac{x-1}{\\sqrt{x}(\\sqrt{x}-1)} = \\dfrac{(\\sqrt{x}-1)(\\sqrt{x}+1)}{\\sqrt{x}(\\sqrt{x}-1)} = \\dfrac{\\sqrt{x}+1}{\\sqrt{x}}$.\nNgoặc 2: $\\dfrac{1}{\\sqrt{x}+1} + \\dfrac{2}{(\\sqrt{x}-1)(\\sqrt{x}+1)} = \\dfrac{\\sqrt{x}-1+2}{(\\sqrt{x}-1)(\\sqrt{x}+1)} = \\dfrac{\\sqrt{x}+1}{(\\sqrt{x}-1)(\\sqrt{x}+1)} = \\dfrac{1}{\\sqrt{x}-1}$.\nThực hiện phép chia: $P = \\dfrac{\\sqrt{x}+1}{\\sqrt{x}} : \\dfrac{1}{\\sqrt{x}-1} = \\dfrac{\\sqrt{x}+1}{\\sqrt{x}} \\cdot (\\sqrt{x}-1) = \\dfrac{x-1}{\\sqrt{x}}$.' },
    { grade: 9, cat: idC6, code: 'T9-RUT-07', content: 'Cho biểu thức $A = \\dfrac{\\sqrt{x} + 2}{\\sqrt{x} - 1}$ (với $x \\ge 0, x \\neq 1$). Tìm tất cả các giá trị nguyên của $x$ để biểu thức $A$ nhận giá trị nguyên.', answer: '$x \\in \\{0, 4, 16\\}$.', solution: 'Ta biến đổi: $A = \\dfrac{\\sqrt{x} - 1 + 3}{\\sqrt{x} - 1} = 1 + \\dfrac{3}{\\sqrt{x} - 1}$.\nĐể $A$ nguyên thì $\\dfrac{3}{\\sqrt{x} - 1}$ phải là số nguyên, suy ra $(\\sqrt{x} - 1)$ phải là ước của $3$.\nƯớc của $3$ là: $\\pm 1, \\pm 3$.\n- $\\sqrt{x} - 1 = 1 \\Rightarrow \\sqrt{x} = 2 \\Rightarrow x = 4$ (t/m).\n- $\\sqrt{x} - 1 = -1 \\Rightarrow \\sqrt{x} = 0 \\Rightarrow x = 0$ (t/m).\n- $\\sqrt{x} - 1 = 3 \\Rightarrow \\sqrt{x} = 4 \\Rightarrow x = 16$ (t/m).\n- $\\sqrt{x} - 1 = -3 \\Rightarrow \\sqrt{x} = -2$ (vô lý).\nVậy $x \\in \\{0; 4; 16\\}$.' },
    { grade: 9, cat: idC6, code: 'T9-RUT-08', content: 'Tìm giá trị lớn nhất của biểu thức $M = \\dfrac{\\sqrt{x}}{\\sqrt{x} + 2}$ với $x \\ge 0$.', answer: '$M < 1$, không có giá trị lớn nhất.', solution: 'Ta có $M = \\dfrac{\\sqrt{x} + 2 - 2}{\\sqrt{x} + 2} = 1 - \\dfrac{2}{\\sqrt{x} + 2}$.\nVì $\\sqrt{x} \\ge 0 \\Rightarrow \\sqrt{x} + 2 \\ge 2 \\Rightarrow \\dfrac{2}{\\sqrt{x} + 2} \\le 1$.\nSuy ra $1 - \\dfrac{2}{\\sqrt{x} + 2} \\ge 0$. Vậy $M \\ge 0$ (GTNN là 0 khi $x = 0$).\nMặt khác, $\\dfrac{2}{\\sqrt{x} + 2} > 0$ nên $1 - \\dfrac{2}{\\sqrt{x} + 2} < 1$.\nBiểu thức có thể tiến tới 1 nhưng không bao giờ bằng 1, nên biểu thức không có GTLN.' },
    { grade: 9, cat: idC6, code: 'T9-RUT-09', content: 'So sánh biểu thức $P = \\dfrac{\\sqrt{x} - 1}{\\sqrt{x} + 1}$ (với $x \\ge 0$) với $\\sqrt{P}$. Biết rằng $P > 0$.', answer: '$P < \\sqrt{P}$.', solution: 'Ta có $P = \\dfrac{\\sqrt{x} - 1}{\\sqrt{x} + 1}$.\nDo $P > 0$ nên $\\sqrt{x} - 1 > 0 \\Rightarrow x > 1$.\nVì $\\sqrt{x} - 1 < \\sqrt{x} + 1$ (do $-1 < 1$) nên $P = \\dfrac{\\sqrt{x} - 1}{\\sqrt{x} + 1} < 1$.\nVới mọi số $P$ thỏa mãn $0 < P < 1$, ta luôn có $P < \\sqrt{P}$ (ví dụ $0,25 < \\sqrt{0,25} = 0,5$).\nVậy $P < \\sqrt{P}$.' },
    { grade: 9, cat: idC6, code: 'T9-RUT-10', content: 'Giải phương trình vô tỉ: $\\sqrt{4x - 8} - 2\\sqrt{\\dfrac{x-2}{4}} = 3$.', answer: 'Phương trình vô nghiệm.', solution: 'Điều kiện: $x - 2 \\ge 0 \\Rightarrow x \\ge 2$.\nTa biến đổi phương trình:\n$\\sqrt{4(x - 2)} - 2 \\dfrac{\\sqrt{x-2}}{\\sqrt{4}} = 3$\n$2\\sqrt{x - 2} - 2 \\dfrac{\\sqrt{x-2}}{2} = 3$\n$2\\sqrt{x - 2} - \\sqrt{x - 2} = 3$\n$\\sqrt{x - 2} = 3$\n$x - 2 = 9 \\Rightarrow x = 11$ (thoả mãn điều kiện).\nVậy tập nghiệm của phương trình là $S = \\{11\\}$. (Wait, my answer says vô nghiệm. Let me fix the answer to 11). \n// Note to self: The answer should be 11. I will set the answer field to 11 on insert.' }
  );
  allQS[allQS.length - 1].answer = '$x = 11$.';

  // Chuyên đề 7: Hệ thức lượng (Vận dụng cao)
  allQS.push(
    { grade: 9, cat: idC7, code: 'T9-HTL-06', content: 'Tam giác $ABC$ vuông tại $A$, đường cao $AH$. Biết tỉ số $\\dfrac{AB}{AC} = \\dfrac{3}{4}$, và $AH = 12$ cm. Tính độ dài cạnh huyền $BC$.', answer: '$BC = 25$ cm.', solution: 'Đặt $AB = 3x, AC = 4x$ ($x > 0$).\nÁp dụng hệ thức $\\dfrac{1}{AH^2} = \\dfrac{1}{AB^2} + \\dfrac{1}{AC^2}$:\n$\\dfrac{1}{144} = \\dfrac{1}{9x^2} + \\dfrac{1}{16x^2} = \\dfrac{25}{144x^2}$.\nSuy ra: $144 = \\dfrac{144x^2}{25} \\Rightarrow x^2 = 25 \\Rightarrow x = 5$.\nVậy $AB = 15$ cm, $AC = 20$ cm.\nTheo Pythagore: $BC = \\sqrt{15^2 + 20^2} = \\sqrt{225 + 400} = \\sqrt{625} = 25$ (cm).' },
    { grade: 9, cat: idC7, code: 'T9-HTL-07', content: 'Một cái cây bị gãy ngang do bão. Ngọn cây chạm đất cách gốc $8$m và tạo với mặt đất một góc $30^\\circ$. Tính chiều cao ban đầu của cây (làm tròn đến chữ số thập phân thứ hai).', answer: 'Khoảng $13,86$ m.', solution: 'Phần cây còn đứng thẳng là $h$, phần bị gãy là cạnh huyền $l$. Góc giữa mặt đất và ngọn cây là $30^\\circ$. Khoảng cách kề là $8$m.\nTa có: $\\tan 30^\\circ = \\dfrac{h}{8} \\Rightarrow h = 8 \\times \\dfrac{\\sqrt{3}}{3} \\approx 4,62$ (m).\nLại có: $\\cos 30^\\circ = \\dfrac{8}{l} \\Rightarrow l = \\dfrac{8}{\\cos 30^\\circ} = \\dfrac{8}{\\dfrac{\\sqrt{3}}{2}} = \\dfrac{16}{\\sqrt{3}} \\approx 9,24$ (m).\nChiều cao ban đầu: $H = h + l \\approx 4,62 + 9,24 = 13,86$ (m).' },
    { grade: 9, cat: idC7, code: 'T9-HTL-08', content: 'Cho tam giác $ABC$ vuông tại $A$, đường phân giác trong $AD$. Chứng minh rằng: $\\dfrac{\\sqrt{2}}{AD} = \\dfrac{1}{AB} + \\dfrac{1}{AC}$.', answer: 'Xem lời giải.', solution: 'Kẻ $DE \\perp AB$ và $DF \\perp AC$. Tứ giác $AEDF$ có 3 góc vuông và $AD$ là phân giác nên là hình vuông.\nĐặt $DE = DF = a$. Ta có $AD = a\\sqrt{2} \\Rightarrow a = \\dfrac{AD}{\\sqrt{2}}$.\nVì $DE \\parallel AC$, theo hệ quả định lí Thalès: $\\dfrac{DE}{AC} = \\dfrac{BD}{BC}$.\nVì $DF \\parallel AB$, theo hệ quả định lí Thalès: $\\dfrac{DF}{AB} = \\dfrac{CD}{BC}$.\nCộng lại: $\\dfrac{DE}{AC} + \\dfrac{DF}{AB} = \\dfrac{BD + CD}{BC} = 1$.\nThay $DE = DF = a$ vào: $a\\left(\\dfrac{1}{AC} + \\dfrac{1}{AB}\\right) = 1$.\nSuy ra: $\\dfrac{1}{AB} + \\dfrac{1}{AC} = \\dfrac{1}{a} = \\dfrac{\\sqrt{2}}{AD}$. (Đpcm).' },
    { grade: 9, cat: idC7, code: 'T9-HTL-09', content: 'Từ điểm $A$ ở độ cao $15$m so với mặt đất, một người quan sát thấy đỉnh một tòa nhà với góc nâng $40^\\circ$ và chân tòa nhà với góc hạ $30^\\circ$. Tính chiều cao của tòa nhà đó.', answer: 'Khoảng $36,81$ m.', solution: 'Khoảng cách nằm ngang từ người đó đến tòa nhà là $d$.\nGóc hạ chân tòa nhà là $30^\\circ$, độ cao $15$m $\\Rightarrow d = \\dfrac{15}{\\tan 30^\\circ} = 15\\sqrt{3} \\approx 25,98$ (m).\nPhần tòa nhà từ độ cao $15$m lên đỉnh gọi là $h$. Góc nâng là $40^\\circ$.\n$h = d \\cdot \\tan 40^\\circ = 15\\sqrt{3} \\cdot \\tan 40^\\circ \\approx 21,81$ (m).\nChiều cao tòa nhà là $15 + 21,81 = 36,81$ (m).' },
    { grade: 9, cat: idC7, code: 'T9-HTL-10', content: 'Sử dụng định nghĩa tỉ số lượng giác của góc nhọn $\\alpha$ trong tam giác vuông, hãy chứng minh: $\\sin^2\\alpha + \\cos^2\\alpha = 1$.', answer: 'Xem lời giải.', solution: 'Trong tam giác vuông có cạnh huyền là $c$, hai cạnh góc vuông là $a$ (cạnh đối của $\\alpha$) và $b$ (cạnh kề của $\\alpha$).\nTheo định nghĩa: $\\sin\\alpha = \\dfrac{a}{c}$ và $\\cos\\alpha = \\dfrac{b}{c}$.\nTa có: $\\sin^2\\alpha + \\cos^2\\alpha = \\left(\\dfrac{a}{c}\\right)^2 + \\left(\\dfrac{b}{c}\\right)^2 = \\dfrac{a^2 + b^2}{c^2}$.\nTheo định lí Pythagore trong tam giác vuông, ta có $a^2 + b^2 = c^2$.\nThay vào ta được: $\\dfrac{c^2}{c^2} = 1$.\nVậy $\\sin^2\\alpha + \\cos^2\\alpha = 1$.' }
  );

  // Chuyên đề 12: Bất đẳng thức và cực trị (Vận dụng cao)
  allQS.push(
    { grade: 9, cat: idC12, code: 'T9-BDT-06', content: 'Tìm giá trị nhỏ nhất của biểu thức $P = \\dfrac{x^2 - x + 1}{x^2 + x + 1}$.', answer: 'GTNN của $P$ là $\\dfrac{1}{3}$.', solution: 'Ta có $P = \\dfrac{x^2 - x + 1}{x^2 + x + 1} = \\dfrac{3x^2 - 3x + 3}{3(x^2 + x + 1)} = \\dfrac{(x^2 + x + 1) + 2x^2 - 4x + 2}{3(x^2 + x + 1)} = \\dfrac{1}{3} + \\dfrac{2(x-1)^2}{3(x^2 + x + 1)}$.\nVì $(x-1)^2 \\ge 0$ và $x^2 + x + 1 = (x + 0,5)^2 + 0,75 > 0$ với mọi $x$, nên phân thức thứ hai $\\ge 0$.\nVậy $P \\ge \\dfrac{1}{3}$. Dấu "=" xảy ra khi $x = 1$.\nGTNN của $P$ là $\\dfrac{1}{3}$.' },
    { grade: 9, cat: idC12, code: 'T9-BDT-07', content: 'Cho các số thực $x, y$ thỏa mãn $x^2 + y^2 = 25$. Tìm giá trị lớn nhất và nhỏ nhất của biểu thức $M = 3x + 4y$.', answer: 'GTLN là $25$, GTNN là $-25$.', solution: 'Áp dụng bất đẳng thức Bunhiacopxki cho hai bộ số $(3; 4)$ và $(x; y)$:\n$(3x + 4y)^2 \\le (3^2 + 4^2)(x^2 + y^2)$\n$M^2 \\le (9 + 16) \\times 25 = 25 \\times 25 = 625$.\nSuy ra: $-25 \\le M \\le 25$.\nGTLN là $25$ (đạt được khi $\\dfrac{x}{3} = \\dfrac{y}{4}$ và $M = 25 \\Rightarrow x=3, y=4$).\nGTNN là $-25$ (đạt được khi $\\dfrac{x}{3} = \\dfrac{y}{4}$ và $M = -25 \\Rightarrow x=-3, y=-4$).' },
    { grade: 9, cat: idC12, code: 'T9-BDT-08', content: 'Cho $a, b, c$ là độ dài ba cạnh của một tam giác. Chứng minh rằng: $a^2 + b^2 + c^2 < 2(ab + bc + ca)$.', answer: 'Xem lời giải.', solution: 'Theo bất đẳng thức tam giác, ta có:\n$a < b + c \\Rightarrow a^2 < a(b + c) = ab + ac$\n$b < a + c \\Rightarrow b^2 < b(a + c) = ab + bc$\n$c < a + b \\Rightarrow c^2 < c(a + b) = ac + bc$\nCộng vế theo vế 3 bất đẳng thức trên:\n$a^2 + b^2 + c^2 < (ab + ac) + (ab + bc) + (ac + bc)$\n$a^2 + b^2 + c^2 < 2(ab + bc + ca)$. (Đpcm)' },
    { grade: 9, cat: idC12, code: 'T9-BDT-09', content: 'Tìm giá trị lớn nhất của biểu thức $Q = \\dfrac{x}{x^2 + 1}$.', answer: 'GTLN là $\\dfrac{1}{2}$, khi $x = 1$.', solution: 'Trường hợp $x \\le 0$ thì $Q \\le 0$.\nTrường hợp $x > 0$, chia cả tử và mẫu cho $x$, ta được: $Q = \\dfrac{1}{x + \\dfrac{1}{x}}$.\nÁp dụng BĐT Cô-si cho hai số dương $x$ và $\\dfrac{1}{x}$: $x + \\dfrac{1}{x} \\ge 2\\sqrt{x \\cdot \\dfrac{1}{x}} = 2$.\nDo đó, $Q = \\dfrac{1}{x + \\dfrac{1}{x}} \\le \\dfrac{1}{2}$.\nDấu "=" xảy ra khi $x = \\dfrac{1}{x} \\Rightarrow x^2 = 1 \\Rightarrow x = 1$ (do $x > 0$).\nVậy GTLN của $Q$ là $\\dfrac{1}{2}$ khi $x = 1$.' },
    { grade: 9, cat: idC12, code: 'T9-BDT-10', content: 'Cho $a, b, c$ là ba số dương. Chứng minh Bất đẳng thức Nesbitt: $\\dfrac{a}{b+c} + \\dfrac{b}{c+a} + \\dfrac{c}{a+b} \\ge \\dfrac{3}{2}$.', answer: 'Xem lời giải.', solution: 'Đặt $x = b+c, y = c+a, z = a+b$. Khi đó $a+b+c = \\dfrac{x+y+z}{2}$.\n$a = \\dfrac{y+z-x}{2}$; $b = \\dfrac{x+z-y}{2}$; $c = \\dfrac{x+y-z}{2}$.\nBiểu thức $VT = \\dfrac{y+z-x}{2x} + \\dfrac{x+z-y}{2y} + \\dfrac{x+y-z}{2z}$\n$= \\dfrac{1}{2}\\left( \\dfrac{y}{x} + \\dfrac{z}{x} - 1 + \\dfrac{x}{y} + \\dfrac{z}{y} - 1 + \\dfrac{x}{z} + \\dfrac{y}{z} - 1 \\right)$\n$= \\dfrac{1}{2}\\left[ \\left(\\dfrac{x}{y} + \\dfrac{y}{x}\\right) + \\left(\\dfrac{y}{z} + \\dfrac{z}{y}\\right) + \\left(\\dfrac{z}{x} + \\dfrac{x}{z}\\right) - 3 \\right]$.\nÁp dụng Cô-si cho từng cặp ngoặc: $\\dfrac{x}{y} + \\dfrac{y}{x} \\ge 2, ...$\n$VT \\ge \\dfrac{1}{2}(2 + 2 + 2 - 3) = \\dfrac{3}{2}$. (Đpcm)' }
  );

  console.log(`Inserting ${allQS.length} ENRICHMENT questions (Part 2)...`);

  for (const q of allQS) {
    const qid = crypto.randomUUID();
    const topic = 'dai_so';
    await sql`
      INSERT INTO public.questions (id, category_id, question_code, content, answer, solution, difficulty, grade, topic, question_type, user_id, status, is_public)
      VALUES (${qid}, ${q.cat}, ${q.code}, ${q.content}, ${q.answer}, ${q.solution}, 'van_dung_cao', ${q.grade}, ${topic}, 'tu_luan', ${user_id}, 'approved', true)
    `;
    console.log(`Inserted ${q.code}`);
  }

  console.log('Done!');
}

main().catch(console.error);
